//Create a function that returns a license badge based on which license is passed in
// If there is no license, return an empty string
function renderLicenseBadge(license) {
  let licenseBadge = '';

  if (license != 'None') {
    licenseBadge = '![License Badge](https://shields.io/badge/license-" + license + "-blueviolet)'
  }

  return licenseBadge;
};

// Create a function that returns the license link
// If there is no license, return an empty string
function renderLicenseLink(license) {
  let licenseLink = '';

  switch(license) {
    case 'Apache':
      licenseLink = 'https://opensource.org/licenses/Apache-2.0';
      break;
    case 'Boost':
      licenseLink = 'https://www.boost.org/LICENSE_1_0.txt';
      break; 
    case 'Eclipse':
      licenseLink = 'https://opensource.org/licenses/EPL-1.0';
      break; 
    case 'IBM':
      licenseLink = 'https://opensource.org/licenses/IPL-1.0';
      break;
    case 'MIT':
      licenseLink = 'https://opensource.org/licenses/MIT';
      break;
    case 'Mozilla':
      licenseLink = 'https://opensource.org/licenses/MPL-2.0';
      break;
    default:
      licenseLink = '';
  }

  return licenseLink;
};

// Create a function that returns the license section of README
// If there is no license, return an empty string
function renderLicenseSection(license) {
  let licenseSection = '';

  if (license != 'None') {
    licenseSection += '## License\n'
    licenseSection += 'Please see' + renderLicenseLink(license) + ' for more information of this license\n'
  }

  return licenseSection;
}

// Create a function to generate markdown for README
function generateMarkdown(data) {
  return `# ${data.title}

## Description
${data.description}
## Table of Contents
- [Description](#description)
- [Installation](#installation)
- [Usage](#usage)
- [License](#license)
- [Contributing](#contributing)
- [Tests](#tests)
- [Questions](#questions)
## Installation
${data.installation}
## Usage
${data.usage}
## Contributing
${data.contributing}
## Tests
${data.tests}
## Questions
${data.questions}<br />
<br />
Find me on GitHub: [${data.username}](https://github.com/${data.username})<br />
<br />
Email me with any questions: ${data.email}<br /><br />
_This README was generated by [README-generator](https://github.com/jpd61/README-generator) 🔥🔥🔥_
    `;
}


module.exports = generateMarkdown;